version: "3.3"
services:
  tp-foyer:
    build: C:\Users\ASUS\Desktop\Devops
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/db?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8089:8089"
    image: "youssefkchaou/tp-foyer"  # Nom d'image en minuscule
    depends_on:
      - docker-mysql
    networks:
      - tpfoyer_network
  # Service pour l'application Angular
  frontend:
    image: youssefkchaou/tpfoyer-front
    container_name: tpfoyer_frontend
    ports:
      - "4222:4222"
    networks:
      - tpfoyer_network
  docker-mysql:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tpfoyer_network
# Déclaration du réseau
networks:
  tpfoyer_network:

# Volume pour persister les données de MySQL
volumes:
  mysql_data:
